name: Chatbot finetune on mosaicml/mpt-7b-chat

on:
  workflow_call:

env:
  REPO_DIR: "/intel-extension-for-transformers"
  REPO_TAG: "latest"
  DOCKER_FILE_NAME: "intel_extension_for_transformers/neural_chat/docker/Dockerfile"
  CONTAINER_NAME: "chatbotfinetune-mpi"
  EXTRA_CONTAINER_NAME: "chatbotinfer"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-ft-mpt-7b
  cancel-in-progress: true

jobs:
  finetuning:
    name: finetuning test
    runs-on: itrex-node
    steps:
      - name: Docker Clean Up
        run: |
          docker ps -a
          if [[ $(docker ps -a | grep -i '${{ env.CONTAINER_NAME }}') ]]; then
              docker start ${{ env.CONTAINER_NAME }}
              echo "remove left files through container ..."
              docker exec ${{ env.CONTAINER_NAME }} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
          fi
          if [[ $(docker ps -a | grep -i '${{ env.EXTRA_CONTAINER_NAME }}'$) ]]; then
              docker start ${{ env.EXTRA_CONTAINER_NAME }}
              echo "remove left files through container ..."
              docker exec ${{ env.EXTRA_CONTAINER_NAME }} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
          fi
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load environment variables
        run: cat ~/itrex-actions-runner/.env >> $GITHUB_ENV

      - name: Build Docker Image
        run: 
          docker build --no-cache ./ --target cpu --build-arg ITREX_VER=${{ github.sha }} -f ${{ env.DOCKER_FILE_NAME }} -t ${{ env.CONTAINER_NAME }}:${{ env.REPO_TAG }} && yes | docker container prune && yes | docker image prune

      - name: Start Docker Container on socket 0
        id: master_container
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-s0")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          numactl --localalloc --physcpubind=0,2,4,6 -- docker run -tid -v ${{ env.CACHE_DIR }}:/root/.cache -v .:/root/chatbot --name="${{ env.CONTAINER_NAME }}-s0" --hostname="chatbotfinetune-container-mpi-s0" ${{ env.CONTAINER_NAME }}:${{ env.REPO_TAG }}
          master=$(docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" "${{ env.CONTAINER_NAME }}-s0")
          echo "master_node=$master" >> $GITHUB_OUTPUT

      - name: Start Docker Container on socket 1
        id: slave_container
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-s1")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          numactl --localalloc --physcpubind=8,10,12,14 -- docker run -tid -v ${{ env.CACHE_DIR }}:/root/.cache -v .:/root/chatbot --name="${{ env.CONTAINER_NAME }}-s1" --hostname="chatbotfinetune-container-mpi-s1" ${{ env.CONTAINER_NAME }}:${{ env.REPO_TAG }}
          slave=$(docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" "${{ env.CONTAINER_NAME }}-s1")
          echo "slave_node=$slave" >> $GITHUB_OUTPUT

      - name: Run Finetuning
        run: |
          sh .github/workflows/script/chatbot/prepare_ft_mpt-7b-chat_mpi.sh ${{ steps.master_container.outputs.master_node }} ${{ steps.slave_container.outputs.slave_node }}
          docker exec "${{ env.CONTAINER_NAME }}-s0" bash -c "cd /root/chatbot; source ./bash_setup.sh; mpirun -f ./hosts2 -n 2 -ppn 1 -genv OMP_NUM_THREADS=48 sh .github/workflows/script/chatbot/start_ft_mpt-7b-chat_mpi.sh"

      - name: Print Logs and Check Finetuning Status
        if: success() || failure()
        run: |
          sh .github/workflows/script/chatbot/finish_ft_mpt-7b-chat_mpi.sh          

      - name: Stop Container
        if: success() || failure()
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-s0")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-s1")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi

      - name: Test Summary
        run: echo "Finetuning completed successfully"
