name: Chatbot finetune on mosaicml/mpt-7b-chat

on:
  workflow_call:

env:
  REPO_DIR: "/intel-extension-for-transformers"
  REPO_TAG: "latest"
  CACHE_DIR: "~/.cache"
  DOCKER_FILE_NAME: "intel_extension_for_transformers/neural_chat/docker/Dockerfile"
  CONTAINER_NAME: "chatbot"
  EXTRA_CONTAINER_NAME: "Test"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-ft-mpt-7b
  cancel-in-progress: true

jobs:
  finetuning:
    name: finetuning test
    runs-on: neuralchat-node
    steps:
      - name: Docker Clean Up
        run: |
          docker ps -a
          if [[ $(docker ps -a | grep -i ^'${{ env.CONTAINER_NAME }}-${{ runner.name }}') ]]; then
            docker_names=$(docker ps -a | grep "${{ env.CONTAINER_NAME }}-${{ runner.name }}" | awk '{print $NF}')
            for docker_name in $(echo -e ${docker_names});
            do 
              docker start ${docker_name}
              echo "remove left files through container ..."
              docker exec ${docker_name} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
            done
          fi
          if [[ $(docker ps -a | grep -i '${{ env.EXTRA_CONTAINER_NAME }}'$) ]]; then
          docker_names=$(docker ps -a | grep "${{ env.EXTRA_CONTAINER_NAME }}" | awk '{print $NF}')
            for docker_name in $(echo -e ${docker_names});
            do 
              docker start ${docker_name}
              echo "remove left files through container ..."
              docker exec ${docker_name} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
            done
          fi
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: 
          ITREX_VER=${{ github.sha }} || true
          
          docker build --no-cache ./ --target cpu --build-arg REPO=${{ github.server_url }}/${{ github.repository }}.git --build-arg ITREX_VER=${{ github.head_ref }} --build-arg http_proxy="${{ vars.HTTP_PROXY_IMAGE_BUILD }}" --build-arg https_proxy="${{ vars.HTTPS_PROXY_DOCKER_BUILD }}" -f intel_extension_for_transformers/neural_chat/docker/Dockerfile -t chatbotfinetune-mpi:latest && yes | docker container prune && yes | docker image prune

      - name: Start Docker Container on socket 0
        id: master_container
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s0")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          numactl --cpunodebind=0 -- docker run -tid -v ${{ env.CACHE_DIR }}:/root/.cache -v ${{ github.workspace }}:/root/chatbot --name="${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s0" --hostname="chatbotfinetune-container-mpi-s0" ${{ env.CONTAINER_NAME }}finetune-mpi:${{ env.REPO_TAG }}
          master=$(docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" "${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s0")
          echo "master_node=$master" >> $GITHUB_OUTPUT

      - name: Start Docker Container on socket 1
        id: slave_container
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s1")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          numactl --cpunodebind=1 -- docker run -tid -v ${{ env.CACHE_DIR }}:/root/.cache -v ${{ github.workspace }}:/root/chatbot --name="${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s1" --hostname="chatbotfinetune-container-mpi-s1" ${{ env.CONTAINER_NAME }}finetune-mpi:${{ env.REPO_TAG }}
          slave=$(docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" "${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s1")
          echo "slave_node=$slave" >> $GITHUB_OUTPUT

      - name: Run Finetuning
        run: |
          bash .github/workflows/script/chatbot/prepare_ft_mpt-7b-chat_mpi.sh ${{ steps.master_container.outputs.master_node }} ${{ steps.slave_container.outputs.slave_node }}
          docker exec "${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s0" bash -c "cd /root/chatbot; bash ./bash_setup.sh; mpirun -f ./hosts2 -n 2 -ppn 1 -genv OMP_NUM_THREADS=48 sh .github/workflows/script/chatbot/start_ft_mpt-7b-chat_mpi.sh"

      - name: Print Logs and Check Finetuning Status
        if: success() || failure()
        run: |
          bash .github/workflows/script/chatbot/finish_ft_mpt-7b-chat_mpi.sh          

      - name: Stop Container
        if: success() || failure()
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s0")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}-${{ runner.name }}finetune-mpi-s1")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi

      - name: Test Summary
        run: echo "Finetuning completed successfully"
