name: Chatbot inference on mosaicml/mpt-7b-chat

on:
  workflow_call:

env:
  REPO_DIR: "/intel-extension-for-transformers"
  REPO_TAG: "latest"
  CACHE_DIR: "~/.cache"
  DOCKER_FILE_NAME: "intel_extension_for_transformers/neural_chat/docker/Dockerfile"
  CONTAINER_NAME: "chatbot"
  EXTRA_CONTAINER_NAME: "Test"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-inf-mpt-7b
  cancel-in-progress: true

jobs:
  inference:
    name: inference test
    runs-on: neuralchat-node
    steps:
      - name: Docker Clean Up
        run: |
          podman ps -a
          if [[ $(podman ps -a | grep -i ^'${{ env.CONTAINER_NAME }}-${{ runner.name }}') ]]; then
            docker_names=$(podman ps -a | grep "${{ env.CONTAINER_NAME }}-${{ runner.name }}" | awk '{print $NF}')
            for docker_name in $(echo -e ${docker_names});
            do 
              podman start ${docker_name}
              echo "remove left files through container ..."
              podman exec ${docker_name} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
            done
          fi
          if [[ $(podman ps -a | grep -i '${{ env.EXTRA_CONTAINER_NAME }}'$) ]]; then
          docker_names=$(podman ps -a | grep "${{ env.EXTRA_CONTAINER_NAME }}" | awk '{print $NF}')
            for docker_name in $(echo -e ${docker_names});
            do 
              podman start ${docker_name}
              echo "remove left files through container ..."
              podman exec ${docker_name} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
            done
          fi

      - name: Checkout
        uses: actions/checkout@v3


      - name: Build Docker Image
        run: 
          ITREX_VER=${{ github.sha }} || true

          podman build --no-cache ./ --target cpu --build-arg REPO=${{ github.server_url }}/${{ github.repository }}.git --build-arg ITREX_VER=${{ github.head_ref }} --build-arg http_proxy="${{ vars.HTTP_PROXY_IMAGE_BUILD }}" --build-arg https_proxy="${{ vars.HTTPS_PROXY_DOCKER_BUILD }}" -f intel_extension_for_transformers/neural_chat/docker/Dockerfile -t chatbotinfer:latest && yes | docker container prune && yes | docker image prune

      - name: Start Docker Container
        run: |
          cid=$(podman ps -q --filter "name=${{ env.CONTAINER_NAME }}-${{ runner.name }}infer")
          if [[ ! -z "$cid" ]]; then podman stop $cid && podman rm $cid; fi
          podman run -tid -v ${{ env.CACHE_DIR }}:/root/.cache -v ${{ github.workspace }}:/root/chatbot --name=${{ env.CONTAINER_NAME }}-${{ runner.name }}infer --hostname="chatbotinfer-container" ${{ env.CONTAINER_NAME }}infer:${{ env.REPO_TAG }}

      - name: Run Inference Test
        run: |
          podman exec ${{ env.CONTAINER_NAME }}-${{ runner.name }}infer bash -c "cd /root/chatbot && conda activate neuralchat; python workflows/chatbot/inference/generate.py --base_model_path \"mosaicml/mpt-7b-chat\" --instructions \"Transform the following sentence into one that shows contrast. The tree is rotten.\" "

      - name: Stop Container
        if: success() || failure()
        run: |
          cid=$(podman ps -q --filter "name=${{ env.CONTAINER_NAME }}-${{ runner.name }}infer")
          if [[ ! -z "$cid" ]]; then podman stop $cid && podman rm $cid; fi

      - name: Test Summary
        run: echo "Inference completed successfully"
