name: Chatbot inference on mosaicml/mpt-7b-chat

on:
  workflow_call:

env:
  REPO_DIR: "/intel-extension-for-transformers"
  REPO_TAG: "latest"
  CACHE_DIR: "~/.cache"
  DOCKER_FILE_NAME: "intel_extension_for_transformers/neural_chat/docker/Dockerfile"
  CONTAINER_NAME: "chatbot"
  EXTRA_CONTAINER_NAME: "Test"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-inf-mpt-7b
  cancel-in-progress: true

jobs:
  inference:
    name: inference test
    runs-on: itrex-node
    steps:
      - name: Docker Clean Up
        run: |
          docker ps -a
          if [[ $(docker ps -a | grep -i ^'${{ env.CONTAINER_NAME }}') ]]; then
            docker_names=$(docker ps -a | grep "${{ env.CONTAINER_NAME }}" | awk '{print $NF}')
            for docker_name in $(echo -e ${docker_names});
            do 
              docker start ${docker_name}
              echo "remove left files through container ..."
              docker exec ${docker_name} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
            done
          fi
          if [[ $(docker ps -a | grep -i '${{ env.EXTRA_CONTAINER_NAME }}'$) ]]; then
          docker_names=$(docker ps -a | grep "${{ env.EXTRA_CONTAINER_NAME }}" | awk '{print $NF}')
            for docker_name in $(echo -e ${docker_names});
            do 
              docker start ${docker_name}
              echo "remove left files through container ..."
              docker exec ${docker_name} bash -c "ls -a ${{ env.REPO_DIR }} && rm -fr ${{ env.REPO_DIR }}/* && rm -fr ${{ env.REPO_DIR }}/.* || true"
            done
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: 
          cat ~/actions-runner/.env >> $GITHUB_ENV


      - name: Build Docker Image
        run: 
          docker build --no-cache ./ --target cpu --build-arg ITREX_VER=${{ github.head_ref }} -f ${{ env.DOCKER_FILE_NAME }} -t ${{ env.CONTAINER_NAME }}infer:${{ env.REPO_TAG }} && yes | docker container prune && yes | docker image prune

      - name: Start Docker Container
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}infer")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          docker run -tid -v ${{ env.CACHE_DIR }}:/root/.cache -v .:/root/chatbot --name=${{ env.CONTAINER_NAME }}infer --hostname="chatbotinfer-container" ${{ env.CONTAINER_NAME }}infer:${{ env.REPO_TAG }}

      - name: Run Inference Test
        run: |
          docker exec ${{ env.CONTAINER_NAME }}infer bash -c "cd /root/chatbot && source activate && conda activate neuralchat; python workflows/chatbot/inference/generate.py --base_model_path \"mosaicml/mpt-7b-chat\" --instructions \"Transform the following sentence into one that shows contrast. The tree is rotten.\" "

      - name: Stop Container
        if: success() || failure()
        run: |
          cid=$(docker ps -q --filter "name=${{ env.CONTAINER_NAME }}infer")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi

      - name: Test Summary
        run: echo "Inference completed successfully"
