name: Pytest using Conda

on:
  pull_request:

jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Test with pytest
      run: |
        pip install pytest
        pip install tests/requirements.txt
        find . -name "test*.py" | sed 's,\.\/,python ,g' | sed 's/$/ --verbose/'  > run.sh
        echo "This step runs in bash"
        ./run.sh
      shell: bash
